spring.application.name=LinuxMonitor
spring.datasource.url=jdbc:postgresql://localhost:5432/monitor
spring.datasource.username=monitor
spring.datasource.password=monitor
spring.jpa.hibernate.ddl-auto=update